import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cloud One-Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Cloud One-Link
        </h1>


        <div className={styles.grid}>
          <a href="/api/auth/login" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Login.</p>
          </a>
          <a href="/profile" className={styles.card}>
            <h2>Profile &rarr;</h2>
            <p>Profile  </p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Sign Up.</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>About</p>
          </a>

        </div>
      </main>
    </div>
  )
}
